name: Run Monitoring Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Monitoring
        run: python main_monitoring.py